[project]
name = "geospatialsciprogrammingproject"
version = "0.1.0"
description = ""
authors = [
    {name = "Meghraj Singh, Abhishek Adhikari"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "geopandas (>=1.1.2,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
